apiVersion: v1
kind: Pod
metadata:
  name: nginx-https
  labels:
    app: nginx
spec:
  containers:
   - name: nginx-pod
     image: nginx
     ports:
      - containerPort: 80  
      - containerPort: 443
     volumeMounts:
      - name: nginx-configmap
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      - name: nginx-secret-tls
        mountPath: /etc/nginx/tls
  volumes:
   - name: nginx-configmap
     configMap:
       name: nginx-config
       items:
        - key: nginx.conf
          path: nginx.conf  
   - name: nginx-secret-tls
     secret:
       secretName: nginx-secret
       items:
        - key: tls.crt
          path: nginx.crt    
        - key: tls.key
          path: nginx.key    

