apiVersion: v1
kind: Pod
metadata:
  name: pod-desafio
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /app
      name: volume-desafio
    resources:    
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
  volumes:        
  - name: volume-desafio
    emptyDir:
      sizeLimit: "300Mi"  

