apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: girus
spec:
  containers:
  - image: nginx
    name: nginx-girus
    ports:
      - containerPort: 80  
  - image: busybox
    name: busybox
    args:
      - sleep
      - "300"  
