apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-web
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 80  
      nodePort: 30002  
  selector:
    app: nginx    
