apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None # Define que o service será do tipo HEADLESS
  selector:
    app: nginx      
