Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"
    #config.vm.provision "shell", path: "script.sh"
  
    ###### Kubernetes #####
    config.vm.define "PICK-K8S01" do |app|
          app.vm.network "public_network"
          app.vm.provider "virtualbox" do |v|
            v.memory = 4096
            v.cpus = 2
            v.name = "PICK-K8S01"
          end
    end      
  end