apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    novo: new
  name: nginx-deployment  
  namespace: "giropops"  
spec:  
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        app: nginx-deployment  
    spec:
      containers:
        - image: nginx:1.16.0
          name: nginx
          resources:
            limits:
              cpu: "0.6"
              memory: "256Mi"   
            requests:  
              cpu: "0.4"
              memory: "64Mi"   
         

